# Generated by Django 4.0.5 on 2022-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pessoa_bairro_pessoa_cep_pessoa_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ende',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='uf',
            field=models.CharField(max_length=2),
        ),
    ]
